"""
BrainCtxWriter — write brain.ctx to disk with helpful comments.
"""

from __future__ import annotations

from pathlib import Path

import yaml


HEADER_COMMENT = """\
# brain.ctx — AI Constitution Standard v1.0
# Generated by brain-ctx (https://manasdb.com)
#
# This file is auto-maintained. The codebase IS the source of truth.
# Only edit: identity.vision, hard_rules, ethics (if needed).
# Everything else is inferred automatically.
#
# Spec: https://github.com/manasdb/brain-ctx
# ─────────────────────────────────────────────────────────────────────
"""

SECTION_COMMENTS = {
    "version":       "# brain.ctx spec version\n",
    "identity":      "\n# ── Project Identity (auto-inferred, you may refine vision) ──────────\n",
    "inference":     "\n# ── Inference Config (what brain.ctx reads automatically) ─────────────\n",
    "trust":         "\n# ── Trust & Agent Permissions ────────────────────────────────────────\n",
    "hard_rules":    "\n# ── Hard Rules (absolute constraints for AI — never violated) ─────────\n# Tip: Use project-wide \"ALWAYS/NEVER\" directives here.\n",
    "ethics":        "\n# ── Ethics & Data Protection ─────────────────────────────────────────\n",
    "truth_sources": "\n# ── Truth Sources (pointers to live facts — never goes stale) ─────────\n",
    "cognitive":     "\n# ── Cognitive Optimizer (adapts context to each AI model) ─────────────\n# Tip: Adding a \"timeline:\" block triggers architecture/decisions focus.\n",
    "dialects":      "\n# ── Model Dialects (per-model instructions) ──────────────────────────\n",
    "mesh":          "\n# ── Federated Mesh (import other projects' constitutions) ─────────────\n",
    "observability": "\n# ── Observability (audit log of AI actions) ──────────────────────────\n",
    "signature":     "\n# ── Cryptographic Signature ──────────────────────────────────────────\n",
}


class BrainCtxWriter:

    @staticmethod
    def write(ctx, path: Path, include_comments: bool = True) -> None:
        data = ctx.to_dict()

        if not include_comments:
            with open(path, "w", encoding="utf-8") as f:
                yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
            return

        lines = [HEADER_COMMENT]
        for key, value in data.items():
            if key in SECTION_COMMENTS:
                lines.append(SECTION_COMMENTS[key])
            block = yaml.dump({key: value}, default_flow_style=False, allow_unicode=True, sort_keys=False)
            lines.append(block)

        path.write_text("".join(lines), encoding="utf-8")
