/**
 * brain.ctx YAML parser for Node.js
 * Reads, writes, and manipulates brain.ctx files.
 */

import * as fs from "fs"
import * as path from "path"
import * as yaml from "js-yaml"
import type { BrainCtxFile } from "../types/index.js"

export const FILENAME = "brain.ctx"

// ── Header comment written to every brain.ctx file ─────────────
const FILE_HEADER = `\
# brain.ctx — AI Constitution Standard v1.0
# Generated by brain-ctx (https://manasdb.com)
#
# HUMAN-WRITTEN: identity.vision, hard_rules, ethics
# AUTO-INFERRED: everything else
#
# Spec: https://github.com/manasdb/brain-ctx
# ─────────────────────────────────────────────────────────────
`

// ── Reader ─────────────────────────────────────────────────────

/**
 * Parse a brain.ctx YAML string into a BrainCtxFile object.
 *
 * @example
 * const data = parseBrainCtx(fs.readFileSync("brain.ctx", "utf-8"))
 */
export function parseBrainCtx(content: string): BrainCtxFile {
  let parsed: unknown
  try {
    parsed = yaml.load(content)
  } catch (e) {
    throw new Error(`Invalid YAML: ${(e as Error).message}`)
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("brain.ctx must be a YAML mapping at its root")
  }
  return parsed as BrainCtxFile
}

/**
 * Load a brain.ctx file from disk.
 *
 * @example
 * const data = loadBrainCtxFile("./brain.ctx")
 * console.log(data.identity.name)
 */
export function loadBrainCtxFile(filePath: string = FILENAME): BrainCtxFile {
  if (!fs.existsSync(filePath)) {
    throw new Error(`brain.ctx not found: ${filePath}`)
  }
  const content = fs.readFileSync(filePath, "utf-8")
  return parseBrainCtx(content)
}

/**
 * Walk up the directory tree to find the nearest brain.ctx file.
 * Returns the file path and parsed data, or null.
 *
 * @example
 * const result = findBrainCtxFile()
 * if (result) console.log(result.data.identity.name)
 */
export function findBrainCtxFile(
  start: string = process.cwd()
): { filePath: string; data: BrainCtxFile } | null {
  let current = path.resolve(start)
  while (true) {
    const candidate = path.join(current, FILENAME)
    if (fs.existsSync(candidate)) {
      return { filePath: candidate, data: loadBrainCtxFile(candidate) }
    }
    const parent = path.dirname(current)
    if (parent === current) return null
    current = parent
  }
}

// ── Writer ─────────────────────────────────────────────────────

/**
 * Serialize a BrainCtxFile to a YAML string.
 *
 * @example
 * const yaml = serializeBrainCtx(data)
 * fs.writeFileSync("brain.ctx", yaml)
 */
export function serializeBrainCtx(
  data: BrainCtxFile,
  includeHeader = true
): string {
  // Remove empty/undefined fields
  const clean = removeEmpty(data)
  const body  = yaml.dump(clean, { lineWidth: 100, sortKeys: false, noRefs: true })
  return includeHeader ? FILE_HEADER + "\n" + body : body
}

/**
 * Write a BrainCtxFile to disk.
 *
 * @example
 * writeBrainCtxFile(data, "./brain.ctx")
 */
export function writeBrainCtxFile(
  data: BrainCtxFile,
  filePath: string = FILENAME,
  includeHeader = true
): void {
  fs.writeFileSync(filePath, serializeBrainCtx(data, includeHeader), "utf-8")
}

/**
 * Merge two BrainCtxFile objects.
 * Local fields always win over imported fields (local_wins policy).
 *
 * @example
 * const merged = mergeBrainCtx(localData, importedData)
 */
export function mergeBrainCtx(
  local: BrainCtxFile,
  imported: Partial<BrainCtxFile>
): BrainCtxFile {
  return {
    ...imported,
    ...local,
    // Deep merge arrays (append imported, deduplicate)
    hard_rules: deduplicate([
      ...(imported.hard_rules ?? []),
      ...(local.hard_rules    ?? []),
    ]),
    // Deep merge trust (local wins)
    trust: { ...(imported.trust ?? {}), ...(local.trust ?? {}) },
    // Deep merge ethics (local wins)
    ethics: { ...(imported.ethics ?? {}), ...(local.ethics ?? {}) },
  }
}

// ── Helpers ────────────────────────────────────────────────────

function removeEmpty(obj: unknown): unknown {
  if (Array.isArray(obj)) {
    return obj.length > 0 ? obj.map(removeEmpty) : undefined
  }
  if (obj !== null && typeof obj === "object") {
    const result: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
      const cleaned = removeEmpty(v)
      if (cleaned !== undefined && cleaned !== null) {
        if (typeof cleaned === "object" && !Array.isArray(cleaned) && Object.keys(cleaned as object).length === 0) continue
        result[k] = cleaned
      }
    }
    return Object.keys(result).length > 0 ? result : undefined
  }
  return obj
}

function deduplicate(items: string[]): string[] {
  return [...new Set(items)]
}
